### PR TITLE
use apl mode from RIDE 4.0

### PR DESCRIPTION
**Pull request by e9gille**
Use the CodeMirror apl mode and the default css from RIDE 4.0

### CODE REVIEW

**Comment by jayfoad** [comment]
Why?

**Comment by e9gille** [comment]
@abrudz showed me his notebook and pointed out that the syntax highlighting was wrong in some cases. I put this together to show how it can be customised. I don't really care if you merge it in.

**Comment by abrudz** [comment]
Other than the change to kernel.py, you are supplying a new file, kernel.js. Where should it be placed and/or which action should be taken for it to have an effect?

**Comment by e9gille** [comment]
It goes with the kernel.json

**Pull request merged**
